version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gopkg.in/confluentinc/confluent-kafka-go.v1
    versions:
    - 1.5.2
