version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: git clone https://github.com/Microsoft/vcpkg.git
      - run: cd vcpkg
      - run: ./bootstrap-vcpkg.sh
      - run: ./vcpkg integrate install
      - run: vcpkg install librdkafka
      - run: go get -v -t -d ./...
      - run: go test -v ./...
